[package]
name = "image_gen"
version = "0.1.0"
authors = ["Stephen Becker IV <github@deathbyescalator.com>"]

[dependencies]
image = "*"
rand = "0.3"
[dependencies.img_hash]
version = "1"
# For interop with `image`:
features = ["rust-image"]

[profile.release]
debug = true
